chore: consolidate lint and built jobs since they mostly overlap.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -50,5 +50,7 @@ jobs:
           repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Set up build.env with phony secrets.
         run: cp build.sample.env build.env
+      - name: Verify no changes from code generation. If this check has failed, run `make generate` and commit the changes.
+        run: "make generate \nif ! git diff --exit-code --quiet ; then \n  echo\n  echo\n  git diff --stat \"HEAD\"\n  echo\n  echo\n  echo 'ERROR: Lint tools caused changes to the working dir. '\n  exit 1\nfi\n"
       - name: make test
         run: make test
