fix: move lint pr check logic to github action.

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -52,5 +52,15 @@ jobs:
           repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Set up build.env with phony secrets.
         run: cp build.sample.env build.env
-      - name: Verify no changes from lint tools. If you're reading this and the check has failed, run `make -f operator.mk pr_check_lint`.
-        run: make -f operator.mk pr_check_lint
+      - name: Verify no changes from lint tools. If you're reading this and the check has failed, run `make -f operator.mk generate`.
+        run: |
+          make -f operator.mk generate 
+          if git diff --exit-code --quiet ; then 
+            echo
+            echo
+            git diff --stat HEAD
+            echo
+            echo
+            echo "ERROR: Lint tools caused changes to the working dir. "
+            exit 1
+          fi
