feat: add lint target to makefile (#101)
Introduce a new makefile target lint which will run generate and all lint checks
Introduce a lint check for go using golanci-lint
Introduce a lint check target for terraform using terraform fmt
Update the lint github action to use the new pr_check_lint target in the makefile

Part of GH-66

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -23,21 +23,6 @@ jobs:
     name: run lint
     runs-on: ubuntu-latest
     steps:
-      - name: Setup Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: '1.19'
-      - name: Install goimports
-        run: go install golang.org/x/tools/cmd/goimports@latest
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          repository: ${{ github.event.pull_request.head.repo.full_name }}
-      - name: Set up build.env with phony secrets.
-        run: cp build.sample.env build.env
-      - name: Verify no changes from lint tools. If you're reading this and the check has failed, run `make pre_commit`.
-        run: make github_lint
       - name: Remove PR Label
         if: "${{ github.event.action == 'labeled' && github.event.label.name == 'tests: run' }}"
         uses: actions/github-script@v6
@@ -54,3 +39,28 @@ jobs:
             } catch (e) {
               console.log('Failed to remove label. Another job may have already removed it!');
             }
+      - name: Setup Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.19'
+      - name: Install goimports
+        run: go install golang.org/x/tools/cmd/goimports@latest
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+      - name: Set up build.env with phony secrets.
+        run: cp build.sample.env build.env
+      - name: Verify no changes from lint tools. If you're reading this and the check has failed, run `make -f operator.mk generate`.
+        run: |
+          make -f operator.mk generate 
+          if git diff --exit-code --quiet ; then 
+            echo
+            echo
+            git diff --stat HEAD
+            echo
+            echo
+            echo "ERROR: Lint tools caused changes to the working dir. "
+            exit 1
+          fi
