feat: commit installer scripts into repo as part of generate, GH-66 (#107)
Now we commit generated installer scripts into the git repo in the `installer/` folder.

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -53,14 +53,4 @@ jobs:
       - name: Set up build.env with phony secrets.
         run: cp build.sample.env build.env
       - name: Verify no changes from lint tools. If you're reading this and the check has failed, run `make -f operator.mk generate`.
-        run: |
-          make -f operator.mk generate 
-          if git diff --exit-code --quiet ; then 
-            echo
-            echo
-            git diff --stat HEAD
-            echo
-            echo
-            echo "ERROR: Lint tools caused changes to the working dir. "
-            exit 1
-          fi
+        run: "make -f operator.mk generate \nif ! git diff --exit-code --quiet ; then \n  echo\n  echo\n  git diff --stat \"HEAD\"\n  echo\n  echo\n  echo 'ERROR: Lint tools caused changes to the working dir. '\n  exit 1\nfi\n"
