chore: add copyright header.

diff --git a/.github/workflows/release-please-updates.yaml b/.github/workflows/release-please-updates.yaml
--- a/.github/workflows/release-please-updates.yaml
+++ b/.github/workflows/release-please-updates.yaml
@@ -1,38 +1,51 @@
-name: Automatic Release Code Cleanup
+# Copyright 2022 Google LLC
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+name: Code Generation for Release PRs
 on:
   pull_request:
   pull_request_target:
     types: [labeled]
-  # possible alternative, trigger on label  'autorelease: pending' instead
+    # possible alternative, trigger on label  'autorelease: pending' instead
 jobs:
   build:
     if: "${{ github.actor == 'release-please' || (github.event.action == 'labeled' && github.event.label.name == 'generate: run')  }}"
     steps:
-    - name: Remove PR Label
-      if: "${{ github.event.action == 'labeled' && github.event.label.name == 'generate: run' }}"
-      uses: actions/github-script@v6
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          try {
-            await github.rest.issues.removeLabel({
-              name: 'tests: run',
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.payload.pull_request.number
-            });
-          } catch (e) {
-            console.log('Failed to remove label. Another job may have already removed it!');
-          }
-    - name: Setup Go
-      uses: actions/setup-go@v3
-      with:
-        go-version: '1.19'
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        ref: ${{ github.event.pull_request.head.sha }}
-        repository: ${{ github.event.pull_request.head.repo.full_name }}
-    - name: Generate code and commit differences
-      run: 'make generate && git diff --exit-code || ( git add . && git commit -m "chore: ensure that code is consistent using make generate" && git push )'
-
+      - name: Remove PR Label
+        if: "${{ github.event.action == 'labeled' && github.event.label.name == 'generate: run' }}"
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            try {
+              await github.rest.issues.removeLabel({
+                name: 'tests: run',
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                issue_number: context.payload.pull_request.number
+              });
+            } catch (e) {
+              console.log('Failed to remove label. Another job may have already removed it!');
+            }
+      - name: Setup Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.19'
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+      - name: Generate code and commit differences
+        run: 'make generate && git diff --exit-code || ( git add . && git commit -m "chore: ensure that code is consistent using make generate" && git push )'
